export const url = "https://fojsmfwpldavxjcqiolu.supabase.co";
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvanNtZndwbGRhdnhqY3Fpb2x1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NzM0NDAsImV4cCI6MjA1MjU0OTQ0MH0.5igUbpYQIayUE743XqXQzSjLXbUT2CSJ_5liJCAnBMs";
